AWSTemplateFormatVersion: "2010-09-09"
Description: "Gabriele Tupini Technical Showcase - AWS Infrastructure Stack"

Parameters:
  ProjectName:
    Type: String
    Default: "gabriele-showcase"
    Description: "Project name used for resource naming"

  DomainName:
    Type: String
    Default: "gabrieletupini.dev"
    Description: "Primary domain name"

  StagingDomainName:
    Type: String
    Default: "staging.gabrieletupini.dev"
    Description: "Staging domain name"

  Environment:
    Type: String
    Default: "production"
    AllowedValues: ["production", "staging", "development"]
    Description: "Environment name"

Mappings:
  RegionMap:
    us-east-1:
      S3WebsiteEndpoint: "s3-website-us-east-1.amazonaws.com"
    us-west-2:
      S3WebsiteEndpoint: "s3-website-us-west-2.amazonaws.com"
    eu-west-1:
      S3WebsiteEndpoint: "s3-website-eu-west-1.amazonaws.com"

Resources:
  # ============================================================================
  # S3 BUCKETS
  # ============================================================================

  ProductionBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${ProjectName}-prod"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: "index.html"
        ErrorDocument: "error.html"
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: "DeleteOldVersions"
            Status: Enabled
            NoncurrentVersionExpirationInDays: 30
          - Id: "AbortIncompleteMultipartUploads"
            Status: Enabled
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 7
      NotificationConfiguration:
        CloudWatchConfigurations:
          - Event: "s3:ObjectCreated:*"
            CloudWatchConfiguration:
              LogGroupName: !Ref WebsiteLogGroup
      Tags:
        - Key: "Project"
          Value: !Ref ProjectName
        - Key: "Environment"
          Value: !Ref Environment
        - Key: "Purpose"
          Value: "Static Website Hosting"

  StagingBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${ProjectName}-staging"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: "index.html"
        ErrorDocument: "error.html"
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: "DeleteOldVersions"
            Status: Enabled
            NoncurrentVersionExpirationInDays: 7
          - Id: "AbortIncompleteMultipartUploads"
            Status: Enabled
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 1
      Tags:
        - Key: "Project"
          Value: !Ref ProjectName
        - Key: "Environment"
          Value: "staging"
        - Key: "Purpose"
          Value: "Static Website Hosting - Staging"

  LogsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${ProjectName}-logs"
      LifecycleConfiguration:
        Rules:
          - Id: "DeleteOldLogs"
            Status: Enabled
            ExpirationInDays: 90
          - Id: "TransitionToIA"
            Status: Enabled
            TransitionInDays: 30
            StorageClass: STANDARD_IA
          - Id: "TransitionToGlacier"
            Status: Enabled
            TransitionInDays: 90
            StorageClass: GLACIER
      Tags:
        - Key: "Project"
          Value: !Ref ProjectName
        - Key: "Purpose"
          Value: "Access Logs Storage"

  # ============================================================================
  # S3 BUCKET POLICIES
  # ============================================================================

  ProductionBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ProductionBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "PublicReadGetObject"
            Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "${ProductionBucket}/*"
          - Sid: "AllowCloudFrontAccess"
            Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${ProductionOriginAccessIdentity}"
            Action: "s3:GetObject"
            Resource: !Sub "${ProductionBucket}/*"

  StagingBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref StagingBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "PublicReadGetObject"
            Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "${StagingBucket}/*"
          - Sid: "AllowCloudFrontAccess"
            Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${StagingOriginAccessIdentity}"
            Action: "s3:GetObject"
            Resource: !Sub "${StagingBucket}/*"

  # ============================================================================
  # CLOUDFRONT DISTRIBUTIONS
  # ============================================================================

  ProductionOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub "OAI for ${ProjectName} production"

  StagingOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub "OAI for ${ProjectName} staging"

  ProductionCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref DomainName
        Origins:
          - DomainName: !Sub
              - "${Bucket}.${S3WebsiteEndpoint}"
              - Bucket: !Ref ProductionBucket
                S3WebsiteEndpoint:
                  !FindInMap [RegionMap, !Ref "AWS::Region", S3WebsiteEndpoint]
            Id: "S3Origin"
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: "http-only"
        DefaultCacheBehavior:
          TargetOriginId: "S3Origin"
          ViewerProtocolPolicy: "redirect-to-https"
          Compress: true
          AllowedMethods: ["GET", "HEAD", "OPTIONS"]
          CachedMethods: ["GET", "HEAD", "OPTIONS"]
          CachePolicyId: "4135ea2d-6df8-44a3-9df3-4b5a84be39ad" # AWS Managed Caching Optimized
          ResponseHeadersPolicyId: "67f7725c-6f97-4210-82d7-5512b31e9d03" # AWS Managed SecurityHeadersPolicy
          OriginRequestPolicyId: "88a5eaf4-2fd4-4709-b370-b4c650ea3fcf" # AWS Managed CORS-S3Origin
        CacheBehaviors:
          - PathPattern: "*.html"
            TargetOriginId: "S3Origin"
            ViewerProtocolPolicy: "redirect-to-https"
            Compress: true
            AllowedMethods: ["GET", "HEAD", "OPTIONS"]
            CachePolicyId: "4135ea2d-6df8-44a3-9df3-4b5a84be39ad"
            TTL: 0
          - PathPattern: "*.css"
            TargetOriginId: "S3Origin"
            ViewerProtocolPolicy: "redirect-to-https"
            Compress: true
            AllowedMethods: ["GET", "HEAD", "OPTIONS"]
            CachePolicyId: "4135ea2d-6df8-44a3-9df3-4b5a84be39ad"
            TTL: 31536000 # 1 year
          - PathPattern: "*.js"
            TargetOriginId: "S3Origin"
            ViewerProtocolPolicy: "redirect-to-https"
            Compress: true
            AllowedMethods: ["GET", "HEAD", "OPTIONS"]
            CachePolicyId: "4135ea2d-6df8-44a3-9df3-4b5a84be39ad"
            TTL: 31536000 # 1 year
          - PathPattern: "/images/*"
            TargetOriginId: "S3Origin"
            ViewerProtocolPolicy: "redirect-to-https"
            Compress: true
            AllowedMethods: ["GET", "HEAD"]
            CachePolicyId: "4135ea2d-6df8-44a3-9df3-4b5a84be39ad"
            TTL: 31536000 # 1 year
        DefaultRootObject: "index.html"
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: "/index.html"
            ErrorCachingMinTTL: 300
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: "/index.html"
            ErrorCachingMinTTL: 300
        Enabled: true
        HttpVersion: "http2"
        IPV6Enabled: true
        PriceClass: "PriceClass_100" # Use only North America and Europe edge locations
        ViewerCertificate:
          AcmCertificateArn: !Ref SSLCertificate
          SslSupportMethod: "sni-only"
          MinimumProtocolVersion: "TLSv1.2_2021"
        Logging:
          Bucket: !GetAtt LogsBucket.DomainName
          Prefix: "cloudfront-logs/production/"
        WebACLId: !GetAtt WebACL.Arn
      Tags:
        - Key: "Project"
          Value: !Ref ProjectName
        - Key: "Environment"
          Value: !Ref Environment
        - Key: "Purpose"
          Value: "CDN Distribution"

  StagingCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref StagingDomainName
        Origins:
          - DomainName: !Sub
              - "${Bucket}.${S3WebsiteEndpoint}"
              - Bucket: !Ref StagingBucket
                S3WebsiteEndpoint:
                  !FindInMap [RegionMap, !Ref "AWS::Region", S3WebsiteEndpoint]
            Id: "S3Origin"
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: "http-only"
        DefaultCacheBehavior:
          TargetOriginId: "S3Origin"
          ViewerProtocolPolicy: "redirect-to-https"
          Compress: true
          AllowedMethods: ["GET", "HEAD", "OPTIONS"]
          CachedMethods: ["GET", "HEAD", "OPTIONS"]
          CachePolicyId: "4135ea2d-6df8-44a3-9df3-4b5a84be39ad"
          ResponseHeadersPolicyId: "67f7725c-6f97-4210-82d7-5512b31e9d03"
          TTL: 300 # 5 minutes for staging
        DefaultRootObject: "index.html"
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: "/index.html"
            ErrorCachingMinTTL: 60
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: "/index.html"
            ErrorCachingMinTTL: 60
        Enabled: true
        HttpVersion: "http2"
        IPV6Enabled: true
        PriceClass: "PriceClass_100"
        ViewerCertificate:
          AcmCertificateArn: !Ref SSLCertificate
          SslSupportMethod: "sni-only"
          MinimumProtocolVersion: "TLSv1.2_2021"
        Logging:
          Bucket: !GetAtt LogsBucket.DomainName
          Prefix: "cloudfront-logs/staging/"
      Tags:
        - Key: "Project"
          Value: !Ref ProjectName
        - Key: "Environment"
          Value: "staging"
        - Key: "Purpose"
          Value: "CDN Distribution - Staging"

  # ============================================================================
  # SSL CERTIFICATE
  # ============================================================================

  SSLCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      SubjectAlternativeNames:
        - !Sub "*.${DomainName}"
        - !Ref StagingDomainName
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Ref DomainName
          HostedZoneId: !Ref HostedZone
        - DomainName: !Ref StagingDomainName
          HostedZoneId: !Ref HostedZone
      Tags:
        - Key: "Project"
          Value: !Ref ProjectName
        - Key: "Purpose"
          Value: "SSL Certificate"

  # ============================================================================
  # ROUTE 53 DNS
  # ============================================================================

  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: !Ref DomainName
      HostedZoneConfig:
        Comment: !Sub "Hosted zone for ${ProjectName}"
      HostedZoneTags:
        - Key: "Project"
          Value: !Ref ProjectName
        - Key: "Purpose"
          Value: "DNS Management"

  ProductionDNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        DNSName: !GetAtt ProductionCloudFrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2 # CloudFront hosted zone ID
        EvaluateTargetHealth: false

  ProductionDNSRecordIPv6:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Ref DomainName
      Type: AAAA
      AliasTarget:
        DNSName: !GetAtt ProductionCloudFrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2 # CloudFront hosted zone ID
        EvaluateTargetHealth: false

  StagingDNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Ref StagingDomainName
      Type: A
      AliasTarget:
        DNSName: !GetAtt StagingCloudFrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2 # CloudFront hosted zone ID
        EvaluateTargetHealth: false

  # ============================================================================
  # WAF WEB ACL
  # ============================================================================

  WebACL:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: !Sub "${ProjectName}-web-acl"
      Scope: CLOUDFRONT
      DefaultAction:
        Allow: {}
      Rules:
        - Name: "AWSManagedRulesCommonRuleSet"
          Priority: 1
          OverrideAction:
            None: {}
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: !Sub "${ProjectName}CommonRuleSet"
        - Name: "RateLimitRule"
          Priority: 2
          Action:
            Block: {}
          Statement:
            RateBasedStatement:
              Limit: 1000
              AggregateKeyType: IP
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: !Sub "${ProjectName}RateLimit"
      VisibilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: !Sub "${ProjectName}WebACL"
      Tags:
        - Key: "Project"
          Value: !Ref ProjectName
        - Key: "Purpose"
          Value: "Web Application Firewall"

  # ============================================================================
  # CLOUDWATCH MONITORING
  # ============================================================================

  WebsiteLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/s3/${ProjectName}"
      RetentionInDays: 30

  PerformanceAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${ProjectName}-high-error-rate"
      AlarmDescription: "High error rate detected"
      MetricName: "OriginLatency"
      Namespace: "AWS/CloudFront"
      Statistic: "Average"
      Period: 300
      EvaluationPeriods: 2
      Threshold: 1000
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: "DistributionId"
          Value: !Ref ProductionCloudFrontDistribution
      TreatMissingData: notBreaching

  # ============================================================================
  # IAM ROLES FOR CI/CD
  # ============================================================================

  DeploymentRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${ProjectName}-deployment-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Sub "arn:aws:iam::${AWS::AccountId}:oidc-provider/token.actions.githubusercontent.com"
            Action: "sts:AssumeRoleWithWebIdentity"
            Condition:
              StringEquals:
                "token.actions.githubusercontent.com:aud": "sts.amazonaws.com"
              StringLike:
                "token.actions.githubusercontent.com:sub": "repo:gabriele-tupini/showcase:*"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/CloudFrontFullAccess"
      Policies:
        - PolicyName: "S3DeploymentAccess"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "s3:GetObject"
                  - "s3:PutObject"
                  - "s3:DeleteObject"
                  - "s3:ListBucket"
                Resource:
                  - !Sub "${ProductionBucket}/*"
                  - !Sub "${StagingBucket}/*"
                  - !Ref ProductionBucket
                  - !Ref StagingBucket
      Tags:
        - Key: "Project"
          Value: !Ref ProjectName
        - Key: "Purpose"
          Value: "CI/CD Deployment Role"

Outputs:
  ProductionBucketName:
    Description: "Production S3 bucket name"
    Value: !Ref ProductionBucket
    Export:
      Name: !Sub "${AWS::StackName}-production-bucket"

  StagingBucketName:
    Description: "Staging S3 bucket name"
    Value: !Ref StagingBucket
    Export:
      Name: !Sub "${AWS::StackName}-staging-bucket"

  ProductionDistributionId:
    Description: "Production CloudFront distribution ID"
    Value: !Ref ProductionCloudFrontDistribution
    Export:
      Name: !Sub "${AWS::StackName}-production-distribution-id"

  StagingDistributionId:
    Description: "Staging CloudFront distribution ID"
    Value: !Ref StagingCloudFrontDistribution
    Export:
      Name: !Sub "${AWS::StackName}-staging-distribution-id"

  ProductionDomainName:
    Description: "Production CloudFront domain name"
    Value: !GetAtt ProductionCloudFrontDistribution.DomainName
    Export:
      Name: !Sub "${AWS::StackName}-production-domain"

  StagingDomainName:
    Description: "Staging CloudFront domain name"
    Value: !GetAtt StagingCloudFrontDistribution.DomainName
    Export:
      Name: !Sub "${AWS::StackName}-staging-domain"

  HostedZoneId:
    Description: "Route 53 hosted zone ID"
    Value: !Ref HostedZone
    Export:
      Name: !Sub "${AWS::StackName}-hosted-zone-id"

  SSLCertificateArn:
    Description: "SSL certificate ARN"
    Value: !Ref SSLCertificate
    Export:
      Name: !Sub "${AWS::StackName}-ssl-certificate-arn"

  WebsiteURL:
    Description: "Production website URL"
    Value: !Sub "https://${DomainName}"
    Export:
      Name: !Sub "${AWS::StackName}-website-url"

  StagingURL:
    Description: "Staging website URL"
    Value: !Sub "https://${StagingDomainName}"
    Export:
      Name: !Sub "${AWS::StackName}-staging-url"
